### ISSUE TITLE
Clean onAlternative state method

### ISSUE THREAD

**Issue by JulianParrillaBabel** [babel-cdm/EMA#25]
In some cases, the alternative state gets stuck in one point, that forces create a new state to clean.

How reproduce issue:

Show dialog with onAlternative, navigate up, go back and dialog is show again.

**Comment by carlosmateo89** [comment]
Is the normal behaviour. The problem is that you don't have update the state to normal, so the alternative state is on and for that reason when the view is recreated the dialog appear. You have to update the state to normal just before navigate to other view. Just use updateToNormalState()
