### ISSUE TITLE
Viewbinding support

### ISSUE THREAD

**Issue by babeljmartin** [babel-cdm/EMA#31]
Removing the view inflating (activities and fragments) is needed to allow view binding. Cause view binding needs to inflate the view by itself. A view can not be inflated twice cause throws duplicate ids error.

**Comment by jeluchu** [comment]
@babeljmartin I have migrated synthetic links, as they were currently deprecated, so ViewBinding support is now included in a simple way. I invite you to check the pull request I have made: #38

**Comment by jeluchu** [comment]
Issue closed due to implementation in v2.5.0
